Payments:
  enable: false
  create: 20.00
  delete: 0.00
  claim: 10.00
  add: 5.00
  remove: 0.00
Refunds:
  enable: false
  delete: 10.00
  unclaim: 5.00
Message:
  charged: 'You were charged <amount> for that.'
  chargefail: 'You need <amount> to do that.'
  refunded: 'You have been refunded <amount>!'