name: SimpleTownsEconomy
main: markehme.SimpleTownsEconomy.SimpleTownsEconomy
author: MarkehMe
website: http://markeh.me
version: 1.0.0
depend: [ SimpleTowns, Vault ]
dev-url: http://dev.bukkit.org/bukkit-plugins/simpletownseconomy/